version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      dependency-type: "development"
    groups:
      development-dependencies:
        dependency-type: "development"
